### ISSUE TITLE
BREAKING with latest Android SDK 22.0.0 release

### ISSUE THREAD

**Issue by RobertBrunhage** [braze-inc/braze-flutter-sdk#24]
We are using version `2.5.0` in our project and this morning we started getting issues with `IEventSubscriber` regarding its import which seems to be updated here: https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#2100

I don't expect us to get this breaking change without any updates to the package on the Flutter side. Even updating the import and running the project makes `flutter run` fail silently

This is running in verbose mode and it suddenly just quits.
```
[        ] "flutter run" took 97,706ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

```

**Comment by RobertBrunhage** [comment]
Seems like we had some old native code laying around that defined the latest version for the android sdk. Marking this as closed!
