### ISSUE TITLE
[Bug]: Versions older than 11.0.0 have excessive connection consumption with Firebase Messaging android.net.ConnectivityManager$TooManyRequestsException

### ISSUE THREAD

**Issue by JulianP911** [braze-inc/braze-flutter-sdk#94]
### Which Platforms?

iOS

### Which Flutter Version?

3.19.5

### Which Braze Flutter SDK version?

11.0.0 and 11.0.1

### Repro Rate

100% when running testing

### Steps To Reproduce

flutter pub get
flutter test test.dart

### Expected Behavior

The desired behavior is that the execution of the tests is performed as expected without having to open many connections to Firebase, but on the contrary to have only one for the execution to be successful.

### Actual Incorrect Behavior

The current behavior causes Braze to open multiple connections to Firebase when running flutter tests so it will generate an exception that causes the tests not to run.

### Verbose Logs

```shell
10-24 09:55:42.553 30930 30930 E Zygote : process_name_ptr:30930 com.xiaomi.mtb
10-24 09:55:42.554 30930 30930 E zygote64: Failed to parse /product/etc/mfz.xml: Tinyxml2 error (3): Error=XML_ERROR_FILE_NOT_FOUND ErrorID=3 (0x3) Line number=0: filename=/product/etc/mfz.xml
10-24 09:55:42.554 30930 30930 E zygote64: MemoryFreeze XMLFile not found
10-24 09:55:42.561 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.527 1005 1005 D Zygote : Forked child process 30930
10-24 09:55:42.565 1857 2103 D Boost : hostingType=service, hostingName={com.xiaomi.mtb/com.xiaomi.mtb.modemdump.ModemDumpCollectService}, callerPackage=com.xiaomi.mtb, isSystem=true, isBoostNeeded=false.
10-24 09:55:42.565 1857 2103 W ActivityManager: Slow operation: 54ms so far, now at startProcess: returned from zygote!
10-24 09:55:42.565 1857 2103 W ActivityManager: Slow operation: 54ms so far, now at startProcess: done updating battery stats
10-24 09:55:42.565 1857 2103 W ActivityManager: Slow operation: 54ms so far, now at startProcess: building log message
10-24 09:55:42.565 1857 2103 I ActivityManager: Start proc 30930:com.xiaomi.mtb/1000 for service {com.xiaomi.mtb/com.xiaomi.mtb.modemdump.ModemDumpCollectService} caller=com.xiaomi.mtb
10-24 09:55:42.566 1857 2103 W ActivityManager: Slow operation: 54ms so far, now at startProcess: starting to update pids map
10-24 09:55:42.566 1857 2103 W ActivityManager: Slow operation: 55ms so far, now at startProcess: done updating pids map
10-24 09:55:42.567 30625 30625 D BluetoothHidHost: Proxy object connected
10-24 09:55:42.568 30930 30930 I com.xiaomi.mtb: Using CollectorTypeCC GC.
10-24 09:55:42.571 30625 30658 D BluetoothHeadset: Proxy object connected
10-24 09:55:42.572 29529 23811 D BluetoothHidHostService: getDevicesMatchingConnectionStates()
10-24 09:55:42.572 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.573 30625 30625 D BluetoothHidDevice: Proxy object connected
10-24 09:55:42.576 30930 30930 E com.xiaomi.mtb: Not starting debugger since process cannot load the jdwp agent.
10-24 09:55:42.580 30930 30930 D nativeloader: Load libframework-connectivity-tiramisu-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity-t.jar: ok
10-24 09:55:42.583 30625 30625 D BluetoothHeadset: getConnectedDevices()
10-24 09:55:42.585 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.590 30930 30930 W System.err: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
10-24 09:55:42.590 1139 15643 I WVCdm : [file_utils.cpp(40):Exists] stat failed: ENOENT
10-24 09:55:42.590 30930 30930 W System.err: at libcore.io.Linux.open(Native Method)
10-24 09:55:42.590 30930 30930 W System.err: at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
10-24 09:55:42.590 29529 23811 W HeadsetService: LE Audio not enabled
10-24 09:55:42.590 30930 30930 W System.err: at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
10-24 09:55:42.590 30930 30930 W System.err: at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
10-24 09:55:42.590 30930 30930 W System.err: at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8288)
10-24 09:55:42.590 30930 30930 W System.err: at android.system.Os.open(Os.java:494)
10-24 09:55:42.590 30930 30930 W System.err: at android.os.perfdebug.PerfDebugMonitorImpl.monitorVersionControl(PerfDebugMonitorImpl.java:204)
10-24 09:55:42.590 30930 30930 W System.err: at android.os.perfdebug.PerfDebugMonitorImpl.prepareMonitor(PerfDebugMonitorImpl.java:185)
10-24 09:55:42.590 30930 30930 W System.err: at android.app.ActivityThread.main(ActivityThread.java:8375)
10-24 09:55:42.590 30930 30930 W System.err: at java.lang.reflect.Method.invoke(Native Method)
10-24 09:55:42.590 30930 30930 W System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
10-24 09:55:42.590 30930 30930 W System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
10-24 09:55:42.590 1139 15643 I QCOM-OEMCrypto: Closed session: 1000
10-24 09:55:42.591 30930 30930 I MessageMonitor: Load libmiui_runtime
10-24 09:55:42.592 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.594 29325 30798 E DrmHalAidl: Failed to get vendor from drm plugin: -1010
10-24 09:55:42.594 29325 30798 E DrmHalAidl: Failed to get description from drm plugin: -1010
10-24 09:55:42.599 29529 23811 D HeadsetService: isUnderTiramisuSdk 33 package com.xiaomi.bluetooth
10-24 09:55:42.600 30625 30625 D BluetoothPan: Proxy object connected
10-24 09:55:42.600 1139 15643 E WVCdm : [wv_content_decryption_module.cpp(398):GetMetricsInternal] Cdm Identifier not found
10-24 09:55:42.600 30605 30859 W System.err: INFO: com.whatsapp.net.logging.a.a(WtLog.java:10) : Handshake complete : session_resumed false early_data_sent false early_data_accepted false client_cert_requested false time_ms 386
10-24 09:55:42.601 30625 30625 D BluetoothPbap: Proxy object connected
10-24 09:55:42.602 30625 30625 D MiuiFastConnectService: onReceive: action = android.net.wifi.STATE_CHANGE
10-24 09:55:42.603 30625 30625 D MiuiFastConnectService: Connect_state: CONNECTED
10-24 09:55:42.605 1139 15643 E WVCdm : [wv_content_decryption_module.cpp(457):CloseCdm] Cdm Identifier not found
10-24 09:55:42.605 1139 15643 E WVCdm : Failed to close cdm. status 12
10-24 09:55:42.605 1857 1914 I SmartPower.com.xiaomi.mtb/1000(30930): died->invisible(1097ms) R(process start ) adj=-10000.
10-24 09:55:42.607 1139 15643 I WVCdm : [(0):] L3 Terminate.
10-24 09:55:42.607 1139 30922 I QCOM-OEMCrypto: Exit OEMCrypto idle_thread
10-24 09:55:42.607 1857 1914 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 1000; state: DISABLED
10-24 09:55:42.607 1857 1914 D CompatibilityInfo: mCompatibilityFlags - 0
10-24 09:55:42.607 1857 1914 D CompatibilityInfo: applicationDensity - 440
10-24 09:55:42.607 1857 1914 D CompatibilityInfo: applicationScale - 1.0
10-24 09:55:42.608 1139 15643 I QCOM-OEMCrypto: OEMCrypto_Terminate
10-24 09:55:42.608 1139 15643 I QCOM-OEMCrypto: Cleanup OEMCrypto library
10-24 09:55:42.610 1139 15643 I QCOM-OEMCrypto: Freed all scratch buffers
10-24 09:55:42.619 1857 1914 D CompatibilityInfo: mCompatibilityFlags - 0
10-24 09:55:42.619 1857 1914 D CompatibilityInfo: applicationDensity - 440
10-24 09:55:42.619 1857 1914 D CompatibilityInfo: applicationScale - 1.0
10-24 09:55:42.622 1857 2102 D CompatibilityInfo: mCompatibilityFlags - 0
10-24 09:55:42.622 1857 2102 D CompatibilityInfo: applicationDensity - 440
10-24 09:55:42.622 1857 2102 D CompatibilityInfo: applicationScale - 1.0
10-24 09:55:42.623 1857 2102 W ActivityManager: Rescheduling restart of crashed service com.android.vending/com.google.android.finsky.developergroupidinfo.DeveloperGroupIdInfoService in 775258ms for other
10-24 09:55:42.624 30930 30930 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 1000; state: ENABLED
10-24 09:55:42.629 29325 29325 D FRCPlugin: Sending fetchTimeout: 60
10-24 09:55:42.643 30625 30865 D MiuiCloudControl: local major version: 2, remote major version: 2
10-24 09:55:42.644 30625 30865 D MiuiCloudControl: local minor version: 24, remote minor version: 12
10-24 09:55:42.646 1857 1914 D ConnectivityService: requestNetwork for uid/pid:10836/29325 activeRequest: null callbackRequest: 77976 [NetworkRequest [ REQUEST id=77977, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10836 RequestorUid: 10836 RequestorPkg: qa.tyba.app UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647 isUidTracked: false declaredMethods: 0xffffffff
10-24 09:55:42.650 29325 29763 W DynamiteModule: Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
10-24 09:55:42.650 29325 29325 D Analytics: Ran TrackPayload{event="Application Installed"} on integration Segment.io in 1202500 ns.
10-24 09:55:42.651 29325 29325 D Analytics: Ran TrackPayload{event="Application Opened"} on integration Segment.io in 81198 ns.
10-24 09:55:42.662 29325 29325 D AndroidRuntime: Shutting down VM
10-24 09:55:42.674 27393 27404 W ProviderHelper: Unknown dynamite feature providerinstaller.dynamite
10-24 09:55:42.676 29325 29325 E AndroidRuntime: FATAL EXCEPTION: main
10-24 09:55:42.676 29325 29325 E AndroidRuntime: Process: qa.tyba.app, PID: 29325
10-24 09:55:42.676 29325 29325 E AndroidRuntime: java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.0).
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:546)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda6.run(Unknown Source:2)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:942)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:211)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.os.Looper.loop(Looper.java:300)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8410)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: Caused by: java.lang.RuntimeException: android.net.ConnectivityManager$TooManyRequestsException
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:333)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda2.run(Unknown Source:4)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at java.lang.Thread.run(Thread.java:1012)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: Caused by: android.net.ConnectivityManager$TooManyRequestsException
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4460)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4735)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:5380)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:5347)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:5321)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.remote.AndroidConnectivityMonitor.configureNetworkMonitoring(AndroidConnectivityMonitor.java:87)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.remote.AndroidConnectivityMonitor.(AndroidConnectivityMonitor.java:64)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.remote.RemoteComponenetProvider.createConnectivityMonitor(RemoteComponenetProvider.java:94)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.remote.RemoteComponenetProvider.initialize(RemoteComponenetProvider.java:41)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:158)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:284)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0$com-google-firebase-firestore-core-FirestoreClient(FirestoreClient.java:109)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.core.FirestoreClient$$ExternalSyntheticLambda17.run(Unknown Source:10)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:445)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda0.call(Unknown Source:2)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:330)
10-24 09:55:42.676 29325 29325 E AndroidRuntime: ... 8 more
10-24 09:55:42.675 29325 29325 W qa.tyba.app: type=1400 audit(0.0:793260): avc: denied { search } for name="miuilog" dev="dm-40" ino=1900815 scontext=u:r:untrusted_app:s0:c68,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=qa.tyba.app
10-24 09:55:42.679 29325 29325 W qa.tyba.app: type=1400 audit(0.0:793261): avc: denied { search } for name="miuilog" dev="dm-40" ino=1900815 scontext=u:r:untrusted_app:s0:c68,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=qa.tyba.app
10-24 09:55:42.679 29325 29325 W qa.tyba.app: type=1400 audit(0.0:793262): avc: denied { search } for name="miuilog" dev="dm-40" ino=1900815 scontext=u:r:untrusted_app:s0:c68,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=qa.tyba.app
10-24 09:55:42.679 29325 29325 W qa.tyba.app: type=1400 audit(0.0:793263): avc: denied { search } for name="miuilog" dev="dm-40" ino=1900815 scontext=u:r:untrusted_app:s0:c68,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=qa.tyba.app
10-24 09:55:42.679 29325 29325 W qa.tyba.app: type=1400 audit(0.0:793264): avc: denied { search } for name="miuilog" dev="dm-40" ino=1900815 scontext=u:r:untrusted_app:s0:c68,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=qa.tyba.app
10-24 09:55:42.682 29325 29325 W OOMEventManagerFK: Failed to mkdir /data/miuilog/stability/memleak/heapdump/
10-24 09:55:42.685 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.696 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.699 29325 29763 I DynamiteModule: Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
10-24 09:55:42.700 29325 29763 W ProviderInstaller: Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
10-24 09:55:42.701 4924 27087 W MQSEventManager: jeoccur
10-24 09:55:42.709 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.709 30625 30865 D MiuiCloudControl: resource version info bucket: bluetoothencrypt, region: [ALL], delay sync data: 777600000
10-24 09:55:42.714 1857 4945 D ConnectivityService: requestNetwork for uid/pid:10387/30608 activeRequest: null callbackRequest: 77978 [NetworkRequest [ REQUEST id=77979, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10387 RequestorUid: 10387 RequestorPkg: com.whatsapp UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647 isUidTracked: false declaredMethods: 0xffffffff
10-24 09:55:42.722 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.727 29325 29763 D nativeloader: Configuring clns-8 for other apk /system/framework/org.apache.http.legacy.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~P5gAvVtv2SHqZ3ls3N1Cvw==/com.google.android.gms-w-mlyKVYCNqOy7v-f85_NQ==/lib/arm64:/data/app/~~P5gAvVtv2SHqZ3ls3N1Cvw==/com.google.android.gms-w-mlyKVYCNqOy7v-f85_NQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
10-24 09:55:42.727 29325 29763 D nativeloader: Extending system_exposed_libraries: libmisys_jni.xiaomi.so:libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libupdateprof.qti.so:libthermalclient.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
10-24 09:55:42.725 1134 1134 D vendor.qti.bluetooth@1.0-ibs_handler: SerialClockVote: vote for UART CLK ON
10-24 09:55:42.731 30625 30625 D MiuiFastConnectService: changeMode: true
10-24 09:55:42.731 1134 1134 D vendor.qti.bluetooth@1.0-uart_transport: SocRxDWakeup: Flow off->Change UART baudrate to 38.4kbs->send 0x00->Change UART baudrate to max->Flow on
10-24 09:55:42.731 1134 1134 I vendor.qti.bluetooth@1.0-uart_transport: ## userial_vendor_ioctl: UART Flow Off
10-24 09:55:42.733 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.735 29325 29763 D nativeloader: Configuring clns-9 for other apk /system/framework/com.android.media.remotedisplay.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~P5gAvVtv2SHqZ3ls3N1Cvw==/com.google.android.gms-w-mlyKVYCNqOy7v-f85_NQ==/lib/arm64:/data/app/~~P5gAvVtv2SHqZ3ls3N1Cvw==/com.google.android.gms-w-mlyKVYCNqOy7v-f85_NQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
10-24 09:55:42.735 29325 29763 D nativeloader: Extending system_exposed_libraries: libmisys_jni.xiaomi.so:libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libupdateprof.qti.so:libthermalclient.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
10-24 09:55:42.737 29325 29763 W qa.tyba.app: Loading /data/misc/apexdata/com.android.art/dalvik-cache/arm64/system@framework@com.android.location.provider.jar@classes.odex non-executable as it requires an image which we failed to load
10-24 09:55:42.739 29325 29763 D nativeloader: Configuring clns-10 for other apk /system/framework/com.android.location.provider.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~P5gAvVtv2SHqZ3ls3N1Cvw==/com.google.android.gms-w-mlyKVYCNqOy7v-f85_NQ==/lib/arm64:/data/app/~~P5gAvVtv2SHqZ3ls3N1Cvw==/com.google.android.gms-w-mlyKVYCNqOy7v-f85_NQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
10-24 09:55:42.739 29325 29763 D nativeloader: Extending system_exposed_libraries: libmisys_jni.xiaomi.so:libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libupdateprof.qti.so:libthermalclient.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
10-24 09:55:42.744 537 537 D lowmemorykiller: No processes to kill with adj score >= 702
10-24 09:55:42.744 4924 5267 D DigestGenerator: digest=============qa.tyba.appjava.lang.RuntimeException: Internal error in Cloud Firestore (XX..).
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$(AsyncQueue.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda.run(Unknown Source:)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.os.Handler.handleCallback(Handler.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.os.Handler.dispatchMessage(Handler.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.os.Looper.loopOnce(Looper.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.os.Looper.loop(Looper.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.app.ActivityThread.main(ActivityThread.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at java.lang.reflect.Method.invoke(Native Method)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: Caused by: java.lang.RuntimeException: android.net.ConnectivityManager$TooManyRequestsException
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$(AsyncQueue.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda.run(Unknown Source:)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at java.util.concurrent.FutureTask.run(FutureTask.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at java.lang.Thread.run(Thread.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: Caused by: android.net.ConnectivityManager$TooManyRequestsException
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.remote.AndroidConnectivityMonitor.configureNetworkMonitoring(AndroidConnectivityMonitor.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.remote.AndroidConnectivityMonitor.(AndroidConnectivityMonitor.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.remote.RemoteComponenetProvider.createConnectivityMonitor(RemoteComponenetProvider.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.remote.RemoteComponenetProvider.initialize(RemoteComponenetProvider.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.core.FirestoreClient.lambda$new$$com-google-firebase-firestore-core-FirestoreClient(FirestoreClient.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.core.FirestoreClient$$ExternalSyntheticLambda.run(Unknown Source:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$(AsyncQueue.java:XX)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda.call(Unknown Source:)
10-24 09:55:42.744 4924 5267 D DigestGenerator: at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$(AsyncQueue.java:XX)
10-24 09:55:42.745 1134 1134 I vendor.qti.bluetooth@1.0-uart_transport: ## userial_vendor_set_baud: 17
10-24 09:55:42.745 1857 2686 D ConnectivityService: NetReassign [77979 : null → 460] [c 1] [a 8] [i 21]
10-24 09:55:42.748 30625 30625 D MiuiFastConnectService: change scan mode: 1
10-24 09:55:42.749 1857 2673 D WifiNetworkFactory: got request NetworkRequest [ REQUEST id=77979, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10387 RequestorUid: 10387 RequestorPkg: com.whatsapp UnderlyingNetworks: Null] ]
10-24 09:55:42.749 1857 2673 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=77979, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10387 RequestorUid: 10387 RequestorPkg: com.whatsapp UnderlyingNetworks: Null] ]
10-24 09:55:42.749 1857 2673 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=77979, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10387 RequestorUid: 10387 RequestorPkg: com.whatsapp UnderlyingNetworks: Null] ]
10-24 09:55:42.749 1857 2673 D MultiInternetWifiNetworkFactory: got request NetworkRequest [ REQUEST id=77979, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10387 RequestorUid: 10387 RequestorPkg: com.whatsapp UnderlyingNetworks: Null] ]
10-24 09:55:42.750 1857 2463 W ActivityTaskManager: Force finishing activity qa.tyba.app/com.tyba.app.tyba_app.MainActivity
```

### Additional Information

Check that the firebase versions are the correct ones.

**Comment by hokstuff** [comment]
Hi @JulianP911,

It sounds like the issues you are experiencing are specific to your current setup. Can you contact support@braze.com with more information including:
1. Your relevant test code that is failing
2. Any additional logs that specifically call `Braze` code
3. A minimally reproducible example (sample project or sample tests) in a fresh environment
4. More information on your firebase setup, including any relevant configuration

Thanks!

**Comment by JulianP911** [comment]
I don't think it is an issue specific to a specific step since it occurs with the integration of firebase for the execution of the test environment. Attached is a trace where you can see the problem in more detail. 

**Which Braze Flutter SDK version?**

- 11.0.0

**Which Firebase Setup version?**

- cloud_firestore: 4.17.2
-  firebase_messaging: 14.9.1
- firebase_remote_config: 4.4.4

**Logs**

<img width="1440" alt="Screenshot 2024-10-28 at 8 31 20 PM" src="https://github.com/user-attachments/assets/d846736b-7321-4d2c-94cc-8b0bf1b7e329">

**Comment by hokstuff** [comment]
I'm closing out this ticket due to its age of ~1 year and since it appears that the issue is specific to the particular integration with Firebase in the project. If you continue to have issues, please contact support@braze.com and send over the requested information as well as your custom `test.dart` file that is running the tests that are failing.

Thanks!
